version: '3.7'
services:

  reference-database:
    image: rwilsonebi/reference-data-db:latest
    restart: always
    ports:
      - "6032:5432"
    networks:
      refdata:

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.2
    restart: always
    environment:
        - HASURA_GRAPHQL_DATABASE_URL=postgres://hasurauser:hasurauser@reference-database:5432/refdata
        - HASURA_GRAPHQL_ENABLE_CONSOLE=true
        - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
        - HASURA_GRAPHQL_UNAUTHORIZED_ROLE="public"
    ports:
      - "8088:8080"
    networks:
      refdata:
            
networks:
  refdata:

