apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: mpi2-reference-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v1.0.0-beta.2
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://hasurauser:hasurauser@reference-database:5432/refdata
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_ENABLE_TELEMETRY
          value: "false"
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          value: "public"
        #- name: HASURA_GRAPHQL_ADMIN_SECRET
        #  value: "mpi2#3478"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
