apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hasura-ingress
  namespace: mpi2-reference-data
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 
    http:
      paths:
      #- path: /hasura(/|$)(.*)
      -  backend:
          serviceName: hasura
          servicePort: 80
